# Generated by Django 5.2.17 on 2026-10-09 13:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_suspects', 'Can view the suspects and the hostile list'), ('view_evidence', 'Can view the evidence: mail headers and subjects, wallet and contracts'), ('manage_settings', 'Can change the Alliance, the contact sources and the thresholds')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ContactSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('alliance', 'Alliance'), ('corporation', 'Corporation')], max_length=16)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(blank=True, max_length=254)),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('kind', 'entity_id'), name='eos_spy_network_unique_source')],
            },
        ),
        migrations.CreateModel(
            name='SpyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostile_below', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='A contact of a ticked source counts as hostile when its standing is below this value.', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('-10')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Hostile below standing')),
                ('alliance', models.ForeignKey(blank=True, help_text='The Alliance whose members are checked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eveonline.eveallianceinfo', verbose_name='Alliance')),
            ],
            options={
                'verbose_name': 'Configuration',
                'default_permissions': (),
            },
        ),
    ]
