# Generated by Django 5.2.17 on 2026-10-09 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_spy_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_suspects', 'Can view the suspects per Corporation'), ('view_evidence', 'Can view the evidence: mail headers and subjects, wallet and contracts'), ('manage_settings', 'Can change the Alliance, the contact sources and the thresholds'))},
        ),
        migrations.AddField(
            model_name='spyconfiguration',
            name='corp_changes_per_year',
            field=models.PositiveSmallIntegerField(default=4, help_text='A character that joined this many Corporations within the last 365 days gets a marker.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)], verbose_name='Corporation changes per year'),
        ),
    ]
