# Generated by Django 5.2.17 on 2026-10-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_spy_network', '0002_corp_changes_per_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built_at', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
