# Generated by Django 5.2.17 on 2026-10-09 17:46

import django.core.validators
import eos_spy_network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos_spy_network', '0003_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spyconfiguration',
            name='ignored_ref_types',
            field=models.JSONField(blank=True, default=eos_spy_network.models.default_ignored_ref_types, help_text='Wallet journal entries of these types count neither as ISK with hostiles nor as a payment.', verbose_name='Ignored wallet entry types'),
        ),
        migrations.AddField(
            model_name='spyconfiguration',
            name='lookback_days',
            field=models.PositiveSmallIntegerField(default=365, help_text="Only the last this many days count: wallet, contracts, mails, the network's payments and former Corporations. Standings change - a hostile today may have been a friend back then. 0 takes everything.", validators=[django.core.validators.MaxValueValidator(3650)], verbose_name='Time frame in days'),
        ),
    ]
